# Python script to convert the policies json file to Bigquery ingestable format
python .\pre_process_json_files.py

# set project id
gcloud config set project-id ds-de-sandbox-66

# upload the file generated by above python script to storage bucket
gsutil cp .\policies.json gs://ds-de-sandbox-66-pi/

# upload the provided claims csv to storage bucket
gsutil cp .\DE_test_claims.csv gs://ds-de-sandbox-66-pi/

# Import the claims csv to BQ, aut detect schema
bq load --autodetect ds-de-sandbox-66:pi.claims gs://ds-de-sandbox-66-pi/DE_test_claims.csv

# Import the claims csv to BQ, pass in a schema file
bq load --source_format=NEWLINE_DELIMITED_JSON --ignore_unknown_values  ds-de-sandbox-66:pi.policies gs://ds-de-sandbox-66-pi/policies.json .\schema.json